---
blank_issues_enabled: false
contact_links:
  - name: Make it Sensational Community Support
    url: https://github.com/developer-academy-unina/Workshop-Make-it-Sensational/discussions
    about: Please ask and answer questions here.
